version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./docker/php/
      dockerfile: Dockerfile
    image: runetsoft
    container_name: runetsoft-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - runetsoft

  db:
    image: postgres:12
    container_name: runetsoft-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_DB: runetsoft
    #    volumes:
    #        - ./docker/db/db.sql:/docker-entrypoint-initdb.d/db.sql
    #        - ./docker/db/data:/var/lib/postgresql/data
    networks:
      - runetsoft

  nginx:
    image: nginx:alpine
    container_name: runetsoft-nginx
    restart: unless-stopped
    ports:
      - 8300:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - runetsoft

networks:
  runetsoft:
    driver: bridge